databases:
  - name: seedsphere
    plan: free
    databaseName: seedsphere
    user: seedsphere

services:
  - type: web
    name: seedsphere
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: seedsphere
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
